version: "3.9"
services:
  minecraft:
    image: quteraz/minecraft-forge:1.16.5-local
    ports:
      - "0.0.0.0:25565:25565"
    entrypoint: "./entrypoint.py"
    volumes:
      - type: volume
        target: /minecraft/config
        source: minecraft_config
      - type: volume
        target: /minecraft/mods
        source: minecraft_mods

volumes:
  minecraft_config:
  minecraft_mods:
