version: "3.9"
services:
  minecraft:
    image: quteraz/minecraft-forge:beta
    ports:
      - "0.0.0.0:25565:25565"
    entrypoint: "./entrypoint.py"
    user: "966:965"
    volumes:
      - type: volume
        target: /minecraft/config
        source: minecraft_config

volumes:
  minecraft_config:
