services:
  minecraft_fabric:
    build:
      context: ./img
      args:
        - USER_ID=969
        - JAVA_VER=22
        - MOD_LOADER=fabric
    image: quteraz/minecraft-fabric:1.21.4-beta
    container_name: minecraft_fabric
    ports:
      - "0.0.0.0:25565:25565"
    networks:
      - frontend
    entrypoint: "./entrypoint.py"
    volumes:
      - type: volume
        target: /app/minecraft/config
        source: minecraft_mod_config
      - type: volume
        target: /app/minecraft/mods
        source: minecraft_mods
      - type: volume
        target: /app/config
        source: minecraft_config
  minecraft_forge:
    build:
      context: ./img
      args:
        - USER_ID=969
        - JAVA_VER=17
        - MOD_LOADER=forge
        - LOADER_LINK=https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.4-49.0.11/forge-1.20.4-49.0.11-installer.jar
    image: quteraz/minecraft-forge:1.20.4-beta
    container_name: minecraft_forge
    ports:
      - "0.0.0.0:25565:25565"
    entrypoint: "./entrypoint.py"
    volumes:
      - type: volume
        target: /app/minecraft/config
        source: minecraft_forge_mod_config
      - type: volume
        target: /app/minecraft/mods
        source: minecraft_forge_mods
      - type: volume
        target: /app/config
        source: minecraft_forge_config

volumes:
  minecraft_config:
  minecraft_mods:
  minecraft_mod_config:
  minecraft_forge_config:
  minecraft_forge_mods:
  minecraft_forge_mod_config:

networks:
      frontend:
        driver: bridge
